#pragma once
#include "../../../Patchables/Offsets.hpp"

class CharacterIntermediate
{
public:
	CLASS_GETTER(float, GetPercentCooldownMod, 0x0)
	CLASS_GETTER(float, GetAbilityHasteMod, 0x18)
	CLASS_GETTER(float, GetPercentCooldownCapMod, 0x30)
	CLASS_GETTER(float, GetPassiveCooldownEndTime, 0x48)
	CLASS_GETTER(float, GetPassiveCooldownTotalTime, 0x60)
	CLASS_GETTER(float, GetFlatPhysicalDamageMod, 0xC0)
	CLASS_GETTER(float, GetPercentPhysicalDamageMod, 0xD8)
	CLASS_GETTER(float, GetPercentBonusPhysicalDamageMod, 0xF0)
	CLASS_GETTER(float, GetPercentBasePhysicalDamageAsFlatBonusMod, 0x108)
	CLASS_GETTER(float, GetFlatMagicDamageMod, 0x120)
	CLASS_GETTER(float, GetPercentMagicDamageMod, 0x138)
	CLASS_GETTER(float, GetFlatMagicReduction, 0x150)
	CLASS_GETTER(float, GetPercentMagicReduction, 0x168)
	CLASS_GETTER(float, GetFlatCastRangeMod, 0x180)
	CLASS_GETTER(float, GetAttackSpeedMod, 0x198)
	CLASS_GETTER(float, GetPercentAttackSpeedMod, 0x1B0)
	CLASS_GETTER(float, GetPercentMultiplicativeAttackSpeedMod, 0x1C8)
	CLASS_GETTER(float, GetBaseAttackDamage, 0x1E0)
	CLASS_GETTER(float, GetBaseAttackDamageSansPercentScale, 0x1F8)
	CLASS_GETTER(float, GetFlatBaseAttackDamageMod, 0x210)
	CLASS_GETTER(float, GetPercentBaseAttackDamageMod, 0x228)
	CLASS_GETTER(float, GetBaseAbilityDamage, 0x240)
	CLASS_GETTER(float, GetCritDamageMultiplier, 0x258)
	CLASS_GETTER(float, GetScaleSkinCoef, 0x270)
	CLASS_GETTER(float, GetDodge, 0x288)
	CLASS_GETTER(float, GetCrit, 0x2A0)
	CLASS_GETTER(float, GetArmor, 0x2D0)
	CLASS_GETTER(float, GetBonusArmor, 0x2E8)
	CLASS_GETTER(float, GetSpellBlock, 0x300)
	CLASS_GETTER(float, GetBonusSpellBlock, 0x318)
	CLASS_GETTER(float, GetHPRegenRate, 0x330)
	CLASS_GETTER(float, GetBaseHPRegenRate, 0x348)
	CLASS_GETTER(float, GetMoveSpeed, 0x360)
	CLASS_GETTER(float, GetMoveSpeedBaseIncrease, 0x378)
	CLASS_GETTER(float, GetAttackRange, 0x390)
	CLASS_GETTER(float, GetFlatBubbleRadiusMod, 0x3A8)
	CLASS_GETTER(float, GetPercentBubbleRadiusMod, 0x3C0)
	CLASS_GETTER(float, GetFlatArmorPenetration, 0x3D8)
	CLASS_GETTER(float, GetPhysicalLethality, 0x3F0)
	CLASS_GETTER(float, GetPercentArmorPenetration, 0x408)
	CLASS_GETTER(float, GetPercentBonusArmorPenetration, 0x420)
	CLASS_GETTER(float, GetPercentCritBonusArmorPenetration, 0x438)
	CLASS_GETTER(float, GetPercentCritTotalArmorPenetration, 0x450)
	CLASS_GETTER(float, GetFlatMagicPenetration, 0x468)
	CLASS_GETTER(float, GetMagicLethality, 0x480)
	CLASS_GETTER(float, GetPercentMagicPenetration, 0x498)
	CLASS_GETTER(float, GetPercentBonusMagicPenetration, 0x4B0)
	CLASS_GETTER(float, GetPercentLifeStealMod, 0x4C8)
	CLASS_GETTER(float, GetPercentSpellVampMod, 0x4E0)
	CLASS_GETTER(float, GetPercentPhysicalVamp, 0x510)
	CLASS_GETTER(float, GetPathfindingRadiusMod, 0x528)
	CLASS_GETTER(float, GetPercentCCReduction, 0x540)
	CLASS_GETTER(float, GetPercentEXPBonus, 0x558)
	CLASS_GETTER(float, GetFlatBaseArmorMod, 0x570)
	CLASS_GETTER(float, GetPARRegenRate, 0x5A0)
	CLASS_GETTER(float, GetFlatBaseSpellBlockMod, 0x588)
	CLASS_GETTER(float, GetPrimaryARBaseRegenRateRep, 0x5B8)
	CLASS_GETTER(float, GetSecondaryARRegenRateRep, 0x5D0)
	CLASS_GETTER(float, GetSecondaryARBaseRegenRateRep, 0x5E8)
	CLASS_GETTER(float, GetPercentDamageToBarracksMinionMod, 0x1A50)
	CLASS_GETTER(float, GetFlatDamageReductionFromBarracksMinionMod, 0x1A68)
	CLASS_GETTER(float, GetIncreasedMoveSpeedMinionMod, 0x1A80)

	void ShowDebugImGuiMenu()
	{
		ImGui::Text("Percent Cooldown Mod: %f", this->GetPercentCooldownMod());
	}
};
